### ISSUE TITLE
Update linux host OS and docker version

### ISSUE THREAD

**Issue by ebolyen** [qiime2/busywork#77]
**Bug Description**
The current version of docker available on the Ubuntu 14.04 LTS channel seems to leak inodes, which is the cause of the out of space errors.

Just running most of the test group on a distribution pipeline causes 70% inode utilization. Even small inode leaks will eventually crash this.

**Steps to reproduce the behavior**
1. Run busywork for several months uninterrupted.

**Computation Environment**
- Ubuntu 14.04

**Comments**
1. We might consider changing the RAID configuration to just pooled (0). This will give us an obscene number of inodes. Recovering the filesystem in the case of disk failure is more or less pointless given this hardware has become more or less exclusively a build system. We can just reprovision it on hardware failure.

**Comment by thermokarst** [comment]
Fixed.
